### ISSUE TITLE
osign_client fails to sign dtbo.img

### ISSUE THREAD

**Issue by Mashopy** [OnePlusOSS/android_kernel_modules_oneplus_mt6983#1]
Hello OnePlus,

I tried to use oplus_build_kernel.sh and at it fails with osign_client dtbo.img signing triggered at https://github.com/OnePlusOSS/android_kernel_modules_oneplus_mt6983/blob/oneplus/mt6983_v_15.0.0_oneplus_pad/kernel/build/oplus_build_kernel.sh#L72

Here the terminal output:
```
<INFO> 2024/12/21 14:15:05 mode: prod
<INFO> 2024/12/21 14:15:05 task client version: 1.1.0
<WARN> 2024/12/21 14:15:05 connect to server: dial tcp: lookup oplus.signagent.adc.com on 10.255.255.254:53: no such host
<WARN> 2024/12/21 14:15:05 retry for 0 times
<WARN> 2024/12/21 14:15:05 connect to server: dial tcp: lookup oplus.signagent.adc.com on 10.255.255.254:53: no such host
<WARN> 2024/12/21 14:15:05 retry for 1 times
<WARN> 2024/12/21 14:15:05 connect to server: dial tcp: lookup oplus.signagent.adc.com on 10.255.255.254:53: no such host
<WARN> 2024/12/21 14:15:05 retry for 2 times
<WARN> 2024/12/21 14:15:05 connect to server: dial tcp: lookup oplus.signagent.adc.com on 10.255.255.254:53: no such host
<WARN> 2024/12/21 14:15:05 retry for 3 times
<WARN> 2024/12/21 14:15:05 connect to server: dial tcp: lookup oplus.signagent.adc.com on 10.255.255.254:53: no such host
<WARN> 2024/12/21 14:15:05 retry for 4 times
<ERROR> 2024/12/21 14:15:05 sign: failed
```

I suppose that this tool is only reserved for OPlus engineers ? It would be a shame since unsigned dtbo.img cannot boot with OnePlus MT6983 devices at all.

**Comment by OnePlusOSSAdmin** [comment]
You could comment that line.
Try following command to disable-verity and flash un-signed img.
`adb  root
adb  disable-verity
adb  reboot
adb  root
adb  remount`

**Comment by Mashopy** [comment]
It doesn’t change anything, the bootloader (lk) refuse to boot if the dtbo sign certs aren’t there and lead to an hardbrick.

Right now we extract these certs from OxygenOS dtbo image to be able to use source built dtbo image but that’s just a workaround
